import Link from "next/link";
import { Card, StatusPill } from "@carvia/ui";
import {
  buildAlertDigestPreview,
  getAlertCenter,
  getNotificationDigestRuns,
  getNotificationPreference
} from "../../lib/alerts";
import { requireOnboardedSession } from "../../lib/auth";
import { saveNotificationPreference, sendTestDigest } from "./actions";

const severityTone = {
  info: "info",
  success: "success",
  warning: "warning"
} as const;

const priorityTone = {
  HIGH: "danger",
  LOW: "info",
  MEDIUM: "warning"
} as const;

function formatStage(stage: string) {
  return stage
    .toLowerCase()
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export default async function AlertsPage() {
  const session = await requireOnboardedSession();
  const todayLabel = new Intl.DateTimeFormat("en-US", { dateStyle: "full" }).format(new Date());
  const [alertCenter, notificationPreference, digestRuns] = await Promise.all([
    getAlertCenter(session.user.companyId!),
    getNotificationPreference(session.user.companyId!),
    getNotificationDigestRuns(session.user.companyId!)
  ]);
  const digestPreview = buildAlertDigestPreview(alertCenter);

  return (
    <main className="min-h-screen bg-[linear-gradient(180deg,#faf8f3_0%,#eff0eb_100%)] px-6 py-10">
      <div className="mx-auto max-w-7xl space-y-6">
        <div>
          <p className="text-xs uppercase tracking-[0.28em] text-[var(--foreground-muted)]">Alerts</p>
          <h1 className="mt-2 text-4xl font-semibold text-[var(--navy)]">Daily review signals</h1>
          <p className="mt-2 max-w-3xl text-sm text-[var(--foreground-muted)]">
            In-app alerts combine due pipeline actions, saved search changes, due follow-up tasks, and buy-ready opportunities so the team can review {todayLabel} from one place.
          </p>
        </div>

        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          {[
            { label: "Actionable", value: String(alertCenter.summary.actionableCount), delta: "Signals requiring attention" },
            { label: "Due Today", value: String(alertCenter.summary.dueTodayCount), delta: `Watchlist and task follow-ups due on ${todayLabel}` },
            { label: "Automation Tasks", value: String(alertCenter.summary.automatedTaskCount), delta: "Due tasks generated by Carvia rules" },
            { label: "Executive", value: String(alertCenter.summary.executiveCount), delta: "Management escalations" }
          ].map((item) => (
            <Card key={item.label} title={item.label}>
              <p className="mt-4 text-3xl font-semibold text-[var(--navy)]">{item.value}</p>
              <p className="mt-2 text-sm text-[var(--foreground-muted)]">{item.delta}</p>
            </Card>
          ))}
        </div>

        <Card title="Executive Escalations">
          <div className="mt-5 space-y-4">
            {alertCenter.executiveAlerts.map((alert) => (
              <div key={alert.id} className="rounded-3xl border border-[var(--border)] bg-[var(--surface-muted)] p-4">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div>
                    <p className="font-medium text-[var(--navy)]">{alert.label}</p>
                    <p className="mt-1 text-sm text-[var(--foreground-muted)]">{alert.description}</p>
                  </div>
                  <StatusPill tone={severityTone[alert.severity as keyof typeof severityTone]}>
                    {alert.id === "lead-conversion" || alert.id === "win-rate" ? `${alert.value}%` : String(alert.value)}
                  </StatusPill>
                </div>
              </div>
            ))}
            <div className="flex flex-wrap gap-3">
              <Link
                href="/management"
                className="rounded-full border border-[var(--border)] bg-white px-4 py-2 text-sm font-medium text-[var(--navy)]"
              >
                Open management
              </Link>
              <Link
                href="/inventory"
                className="rounded-full border border-[var(--border)] bg-white px-4 py-2 text-sm font-medium text-[var(--navy)]"
              >
                Open inventory
              </Link>
            </div>
          </div>
        </Card>

        <div className="grid gap-6 xl:grid-cols-[0.95fr_1.05fr]">
          <Card title="Digest Preferences">
            <form action={saveNotificationPreference} className="mt-5 space-y-4">
              <label className="flex items-center gap-3 text-sm text-[var(--navy)]">
                <input
                  defaultChecked={notificationPreference.digestEnabled}
                  name="digestEnabled"
                  type="checkbox"
                  className="h-4 w-4 rounded border-[var(--border)]"
                />
                Enable daily digest for this company
              </label>

              <label className="block">
                <span className="mb-2 block text-sm font-medium text-[var(--navy)]">Delivery mode</span>
                <select
                  name="deliveryChannel"
                  defaultValue={notificationPreference.deliveryChannel}
                  className="w-full rounded-2xl border border-[var(--border)] bg-white px-4 py-3"
                >
                  <option value="IN_APP">In-app digest</option>
                  <option value="EMAIL_READY">Email-ready digest</option>
                </select>
              </label>

              <label className="block">
                <span className="mb-2 block text-sm font-medium text-[var(--navy)]">Recipient email</span>
                <input
                  name="recipientEmail"
                  defaultValue={notificationPreference.recipientEmail ?? ""}
                  placeholder="buyer-team@example.com"
                  className="w-full rounded-2xl border border-[var(--border)] bg-white px-4 py-3"
                />
              </label>

              <label className="block">
                <span className="mb-2 block text-sm font-medium text-[var(--navy)]">Digest hour (local)</span>
                <input
                  name="sendHourLocal"
                  type="number"
                  min={6}
                  max={22}
                  defaultValue={notificationPreference.sendHourLocal}
                  className="w-full rounded-2xl border border-[var(--border)] bg-white px-4 py-3"
                />
              </label>

              <button
                type="submit"
                className="rounded-full bg-[var(--navy)] px-5 py-3 text-sm font-semibold text-white"
              >
                Save digest preferences
              </button>
            </form>
          </Card>

          <Card title="Digest Preview">
            <div className="mt-5 space-y-4">
              <StatusPill tone={notificationPreference.digestEnabled ? "success" : "warning"}>
                {notificationPreference.digestEnabled ? "Digest active" : "Digest paused"}
              </StatusPill>
              <form action={sendTestDigest}>
                <button
                  type="submit"
                  className="rounded-full bg-[var(--navy)] px-5 py-3 text-sm font-semibold text-white"
                >
                  Run test digest now
                </button>
              </form>
              <div className="rounded-3xl border border-[var(--border)] bg-white p-4">
                <pre className="whitespace-pre-wrap font-mono text-sm text-[var(--foreground)]">{digestPreview}</pre>
              </div>
              <p className="text-sm text-[var(--foreground-muted)]">
                This preview reflects the current in-app alert state on {todayLabel} and can later back email or external delivery.
              </p>
            </div>
          </Card>
        </div>

        <Card title="Recent Digest Runs">
          <div className="mt-5 space-y-4">
            {digestRuns.length === 0 ? (
              <div className="rounded-3xl bg-[var(--surface-muted)] p-5">
                <p className="font-medium text-[var(--navy)]">No digest runs logged yet</p>
                <p className="mt-2 text-sm text-[var(--foreground-muted)]">
                  Run a test digest to create the first delivery log for this company and verify the configured channel.
                </p>
              </div>
            ) : (
              digestRuns.map((run) => (
                <div key={run.id} className="rounded-3xl border border-[var(--border)] bg-[var(--surface-muted)] p-4">
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div>
                      <p className="font-medium text-[var(--navy)]">{run.deliveryChannel.replaceAll("_", " ")}</p>
                      <p className="mt-1 text-sm text-[var(--foreground-muted)]">
                        {run.recipientEmail ?? "In-app only"} | {run.sentAt.toLocaleString("en-US")}
                      </p>
                    </div>
                    <StatusPill tone={run.status === "SENT" ? "success" : "warning"}>{run.status.replaceAll("_", " ")}</StatusPill>
                  </div>
                  <p className="mt-3 text-sm text-[var(--foreground)]">
                    Actionable alerts in run: {run.actionableCount}
                  </p>
                  <div className="mt-4 rounded-2xl border border-[var(--border)] bg-white p-4">
                    <pre className="whitespace-pre-wrap font-mono text-xs text-[var(--foreground)]">{run.preview}</pre>
                  </div>
                </div>
              ))
            )}
          </div>
        </Card>

        <div className="grid gap-6 xl:grid-cols-[1fr_1fr]">
          <Card title="Saved Search Signals">
            <div className="mt-5 space-y-4">
              {alertCenter.searchAlerts.length === 0 ? (
                <div className="rounded-3xl bg-[var(--surface-muted)] p-5">
                  <p className="font-medium text-[var(--navy)]">No alert-enabled searches yet</p>
                  <p className="mt-2 text-sm text-[var(--foreground-muted)]">
                    Enable alerts on saved searches in Market Search to generate sourcing signals here.
                  </p>
                </div>
              ) : (
                alertCenter.searchAlerts.map((alert) => (
                  <div key={alert.id} className="rounded-3xl border border-[var(--border)] bg-[var(--surface-muted)] p-4">
                    <div className="flex flex-wrap items-start justify-between gap-3">
                      <div>
                        <p className="font-medium text-[var(--navy)]">{alert.name}</p>
                        <p className="mt-1 text-sm text-[var(--foreground-muted)]">
                          {[alert.filters.make || "Any make", alert.filters.model || "Any model", alert.filters.fuelType || "Any fuel"].join(" | ")}
                        </p>
                      </div>
                      <StatusPill tone={severityTone[alert.severity]}>
                        {alert.delta > 0 ? `+${alert.delta} new matches` : `${alert.currentResultCount} matches`}
                      </StatusPill>
                    </div>

                    <p className="mt-3 text-sm text-[var(--foreground-muted)]">
                      Previous baseline {alert.lastRunResultCount} | Current result count {alert.currentResultCount}
                    </p>

                    <Link
                      href={`/market-search?make=${encodeURIComponent(alert.filters.make)}&model=${encodeURIComponent(alert.filters.model)}&fuelType=${encodeURIComponent(alert.filters.fuelType)}&transmission=${encodeURIComponent(alert.filters.transmission)}&purchasePriceMax=${encodeURIComponent(alert.filters.purchasePriceMax)}`}
                      className="mt-4 inline-flex rounded-full border border-[var(--border)] bg-white px-4 py-2 text-sm font-medium text-[var(--navy)]"
                    >
                      Open search
                    </Link>
                  </div>
                ))
              )}
            </div>
          </Card>

          <Card title="Due Pipeline Actions">
            <div className="mt-5 space-y-4">
              {alertCenter.duePipelineAlerts.length === 0 ? (
                <div className="rounded-3xl bg-[var(--surface-muted)] p-5">
                  <p className="font-medium text-[var(--navy)]">No due actions today</p>
                  <p className="mt-2 text-sm text-[var(--foreground-muted)]">
                    Set next action dates on watchlist items to turn the acquisition workflow into a scheduled review loop.
                  </p>
                </div>
              ) : (
                alertCenter.duePipelineAlerts.map((alert) => (
                  <div key={alert.id} className="rounded-3xl border border-[var(--border)] bg-[var(--surface-muted)] p-4">
                    <div className="flex flex-wrap items-start justify-between gap-3">
                      <div>
                        <p className="font-medium text-[var(--navy)]">
                          {alert.vehicle ? `${alert.vehicle.make} ${alert.vehicle.model}` : "Tracked vehicle"}
                        </p>
                        <p className="mt-1 text-sm text-[var(--foreground-muted)]">
                          {alert.nextActionAt?.toLocaleDateString("en-US", { dateStyle: "long" }) ?? "No date"} | {formatStage(alert.stage)}
                        </p>
                      </div>
                      <StatusPill tone={priorityTone[alert.priority]}>{alert.priority} priority</StatusPill>
                    </div>

                    <p className="mt-3 text-sm text-[var(--foreground)]">
                      {alert.note ?? "No internal note stored for this watchlist item yet."}
                    </p>

                    <Link
                      href="/watchlist"
                      className="mt-4 inline-flex rounded-full border border-[var(--border)] bg-white px-4 py-2 text-sm font-medium text-[var(--navy)]"
                    >
                      Open watchlist
                    </Link>
                  </div>
                ))
              )}
            </div>
          </Card>
        </div>

        <Card title="Due Follow-up Tasks">
          <div className="mt-5 space-y-4">
            {alertCenter.dueTaskAlerts.length === 0 ? (
              <div className="rounded-3xl bg-[var(--surface-muted)] p-5">
                <p className="font-medium text-[var(--navy)]">No overdue or due tasks</p>
                <p className="mt-2 text-sm text-[var(--foreground-muted)]">
                  Create explicit follow-up tasks from the watchlist or pipeline to track calls, document checks, and pricing reviews.
                </p>
              </div>
            ) : (
              alertCenter.dueTaskAlerts.map((task) => (
                <div key={task.id} className="rounded-3xl border border-[var(--border)] bg-[var(--surface-muted)] p-4">
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div>
                      <div className="flex flex-wrap items-center gap-2">
                        <p className="font-medium text-[var(--navy)]">{task.title}</p>
                        {task.origin === "AUTOMATION" ? <StatusPill tone="info">Automation</StatusPill> : null}
                      </div>
                      <p className="mt-1 text-sm text-[var(--foreground-muted)]">
                        {task.vehicle ? `${task.vehicle.make} ${task.vehicle.model}` : "Tracked vehicle"} | {formatStage(task.stage)}
                      </p>
                    </div>
                    <StatusPill tone={priorityTone[task.priority]}>{task.priority} priority</StatusPill>
                  </div>
                  <p className="mt-3 text-sm text-[var(--foreground)]">
                    {task.assigneeName ?? "Unassigned"} |{" "}
                    {task.dueAt ? task.dueAt.toLocaleDateString("en-US", { dateStyle: "long" }) : "No due date"}
                  </p>
                  <Link
                    href="/tasks"
                    className="mt-4 inline-flex rounded-full border border-[var(--border)] bg-white px-4 py-2 text-sm font-medium text-[var(--navy)]"
                  >
                    Open tasks
                  </Link>
                </div>
              ))
            )}
          </div>
        </Card>

        <Card title="Ready Signals">
          <div className="mt-5 space-y-4">
            {alertCenter.readyToBuyAlerts.length === 0 ? (
              <div className="rounded-3xl bg-[var(--surface-muted)] p-5">
                <p className="font-medium text-[var(--navy)]">No negotiating or buy-ready items</p>
                <p className="mt-2 text-sm text-[var(--foreground-muted)]">
                  Move watchlist items into `Negotiating` or `Ready to buy` to surface execution candidates here.
                </p>
              </div>
            ) : (
              alertCenter.readyToBuyAlerts.map((alert) => (
                <div key={alert.id} className="rounded-3xl border border-[var(--border)] bg-[var(--surface-muted)] p-4">
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div>
                      <p className="font-medium text-[var(--navy)]">
                        {alert.vehicle ? `${alert.vehicle.make} ${alert.vehicle.model}` : "Tracked vehicle"}
                      </p>
                      <p className="mt-1 text-sm text-[var(--foreground-muted)]">{formatStage(alert.stage)}</p>
                    </div>
                    <StatusPill tone={priorityTone[alert.priority]}>{alert.priority} priority</StatusPill>
                  </div>
                </div>
              ))
            )}
          </div>
        </Card>
      </div>
    </main>
  );
}
